import "./globals.css"
import { Inter } from "next/font/google"
import { ThemeProvider } from "@/components/theme-provider"
import { Analytics } from "@/components/analytics"
import { ModeToggle } from "@/components/mode-toggle"
import ActiveLink from "@/components/active-link"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  const links = [
    { href: "/resume", label: "Resume" },
    { href: "/competency", label: "Competency" },
    { href: "/projects", label: "Projects" },
    { href: "/portfolio", label: "Portfolio" },
  ]
  return (
    <html lang="en">
      <body
        className={`antialiased min-h-screen bg-white dark:bg-slate-950 text-slate-900 dark:text-slate-50 ${inter.className}`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="max-w-2xl mx-auto py-10 px-4">
            <header>
              <div className="flex items-center justify-between">
                <ModeToggle />
                <nav className="ml-auto text-base font-medium space-x-4">
                  {links.map((link, i) => (
                    // <Link key={i} href={link.href}>
                    //   <a className={pathname === link.href ? "text-gray-900 dark:text-gray-100" : "text-gray-500 dark:text-gray-400"}>
                    //     {link.label}
                    //   </a>
                    // </Link>
                    <ActiveLink key={i} href={link.href}>
                      {link.label}
                    </ActiveLink>
                  ))}
                </nav>
              </div>
            </header>
            <main>{children}</main>
          </div>
          <Analytics />
        </ThemeProvider>
      </body>
    </html>
  )
}
